/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/editor/index.vue')['default']
    MyImage: typeof import('./src/components/editor/customToolbas/MyImage.vue')['default']
    MyImport: typeof import('./src/components/editor/customToolbas/MyImport.vue')['default']
    MyLink: typeof import('./src/components/editor/customToolbas/MyLink.vue')['default']
    MyMark: typeof import('./src/components/editor/customToolbas/MyMark.vue')['default']
    MyMedia: typeof import('./src/components/editor/customToolbas/MyMedia.vue')['default']
    MyTemplate: typeof import('./src/components/editor/customToolbas/MyTemplate.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
  }
}
